### ISSUE TITLE
CPU uses problem

### ISSUE THREAD

**Issue by ksheetal** [inderpalpatheja/nwdaf#58]
After running the jar it's consuming too much of %CPU use.

**Comment by nikhil-truminds** [comment]
Improved Efficiency of the program drastically.
Average CPU utilization at the moment is 19-20% during the timeframe of evening to morning.

**Comment by ksheetal** [comment]
What's the time delay?

**Comment by nikhil-truminds** [comment]
20 seconds

**Comment by ksheetal** [comment]
Fine. Nikhil :)
