### ISSUE TITLE
Add validation, Exception Handling 

### ISSUE THREAD

**Issue by ksheetal** [inderpalpatheja/nwdaf#59]
please make sure all the validation related to subscription/ unsubscription/All database queries and notification has been added.

**Comment by nikhil-truminds** [comment]
Validations for Subscription, Un-subscription, & Updates done by @nikhil-truminds 
Repository null checks done by @sadafts

**Comment by ksheetal** [comment]
Cool Nikhil.
There are still some null checks and empty values left. like if snssias = "", it's getting accepted. 
Please make sure these things are handled properly.

**Comment by nikhil-truminds** [comment]
Validations improved for subscription & subscription updates.
Now includes type-checking, and enum value range checking as well.
