### ISSUE TITLE
VIRT and RES Memory Graph

### ISSUE THREAD

**Issue by ksheetal** [inderpalpatheja/nwdaf#78]
> Graph is working with static data. Now, we have to do it dynamically from the script.
- Get VIRT, RES values from the script. and try to plot a graph.

**Comment by nikhil-truminds** [comment]
Graph plotted through gnuplot command in both command line terminal, as well as in desktop. 
Virtual and resident memory successfully plotted on a graph. The value range is set in Gigabytes.
